# Get-BrandingStyles.ps1
# EPIC-005 SPEC.md §4.4, §5 — branding injection at render time.
#
# Reads a BrandingConfig (EPIC-037 storage and CRUD; not this ticket) through a
# read interface and produces:
#   1. CSS custom-property overrides that drive the report's design-token layer.
#   2. A cover fragment (logo + watermark HTML) injected before <div id="root">.
#   3. A footer/page-numbers fragment injected inside @page via <style>.
#
# ADR-0016: branding is injected into the HTML *before* Chromium prints, not as
# a separate template set. The stock theme is the fallback when no BrandingConfig
# is supplied or when any field is absent.
#
# Security: no tenant-supplied HTML/JS reaches the renderer.  All values are
# escaped with [System.Net.WebUtility]::HtmlEncode before embedding.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

#region ─── Default / fallback values ─────────────────────────────────────────

$script:DefaultBranding = [PSCustomObject]@{
    PrimaryColour   = '#005a9e'   # stock accent
    SurfaceColour   = '#ffffff'
    TextColour      = '#1a1a1a'
    MutedColour     = '#6b7280'
    LogoUrl         = ''
    WatermarkText   = ''
    FooterText      = 'Confidential – generated by M365-Assess'
    ShowPageNumbers = $true
}

#endregion

#region ─── Public functions ──────────────────────────────────────────────────

function Get-BrandingStyles {
    <#
    .SYNOPSIS
        Produces the branding CSS and HTML fragments for render-time injection.
    .DESCRIPTION
        Given an optional BrandingConfig object (as returned by EPIC-037's
        Get-BrandingConfig cmdlet), emits a hashtable with three keys:

            CssOverrides  – A <style> block that overrides the report's CSS
                            custom properties (--accent, --surface, etc.).
            CoverFragment – An HTML fragment to inject before <div id="root">
                            containing the logo and watermark.
            FooterFragment – A <style> block containing @page rules for footer
                             text and optional page numbers.

        If no BrandingConfig is supplied, or a field is missing, the stock
        defaults defined in $script:DefaultBranding are used transparently.
    .PARAMETER BrandingConfig
        A PSCustomObject with optional fields: PrimaryColour, SurfaceColour,
        TextColour, MutedColour, LogoUrl, WatermarkText, FooterText,
        ShowPageNumbers.  Any absent field falls back to the stock default.
    .OUTPUTS
        [hashtable] with keys CssOverrides, CoverFragment, FooterFragment.
    .EXAMPLE
        Get-BrandingStyles
        # Returns stock-theme fragments.

        $cfg = [PSCustomObject]@{ PrimaryColour = '#c00000'; LogoUrl = 'https://example.com/logo.png' }
        Get-BrandingStyles -BrandingConfig $cfg
    #>
    [CmdletBinding()]
    [OutputType([hashtable])]
    param(
        [Parameter()]
        [PSCustomObject]$BrandingConfig = $null
    )

    $cfg = Merge-BrandingConfig -BrandingConfig $BrandingConfig

    $cssOverrides  = Build-CssOverrides  -Config $cfg
    $coverFragment = Build-CoverFragment -Config $cfg
    $footerFragment = Build-FooterFragment -Config $cfg

    return @{
        CssOverrides   = $cssOverrides
        CoverFragment  = $coverFragment
        FooterFragment = $footerFragment
    }
}

function Inject-BrandingIntoHtml {
    <#
    .SYNOPSIS
        Applies branding fragments into a self-contained HTML report string.
    .DESCRIPTION
        Called by Invoke-ReportRender.ps1 immediately before the HTML is handed
        to Chromium.  Performs three injections:

            1. Inserts CssOverrides immediately after <head>.
            2. Inserts CoverFragment immediately before <div id="root">.
            3. Appends FooterFragment before </body>.

        The function is idempotent: injecting twice is prevented by sentinel
        HTML comments.
    .PARAMETER HtmlContent
        The full HTML string produced by the module's report builder.
    .PARAMETER BrandingConfig
        Optional BrandingConfig (same shape as Get-BrandingStyles).
    .OUTPUTS
        [string] Modified HTML content.
    .EXAMPLE
        $html = Get-Content report.html -Raw
        $branded = Inject-BrandingIntoHtml -HtmlContent $html
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param(
        [Parameter(Mandatory)]
        [string]$HtmlContent,

        [Parameter()]
        [PSCustomObject]$BrandingConfig = $null
    )

    if ($HtmlContent -match '<!--m365-branding-injected-->') {
        return $HtmlContent
    }

    $fragments = Get-BrandingStyles -BrandingConfig $BrandingConfig

    # 1. CSS overrides → after <head>
    $html = $HtmlContent -replace '(<head[^>]*>)', "`$1`n$($fragments.CssOverrides)"

    # 2. Cover fragment → before <div id="root">
    $html = $html -replace '(<div id="root">)', "$($fragments.CoverFragment)`$1"

    # 3. Footer fragment → before </body>
    $html = $html -replace '(</body>)', "$($fragments.FooterFragment)`n<!--m365-branding-injected-->`n`$1"

    return $html
}

#endregion

#region ─── Internal helpers ─────────────────────────────────────────────────

function Merge-BrandingConfig {
    [CmdletBinding()]
    [OutputType([PSCustomObject])]
    param(
        [Parameter()]
        [PSCustomObject]$BrandingConfig
    )

    # Resolve each field defensively: an absent property on the supplied config
    # (partial config) must fall back to the stock default rather than throw
    # under Set-StrictMode -Version Latest.
    $supplied = $null
    if ($null -ne $BrandingConfig) {
        $supplied = $BrandingConfig.PSObject.Properties
    }

    $merged = [ordered]@{}
    foreach ($field in $script:DefaultBranding.PSObject.Properties.Name) {
        $val = $null
        if ($null -ne $supplied) {
            $prop = $supplied[$field]
            if ($null -ne $prop) {
                $val = $prop.Value
            }
        }
        if ($null -eq $val -or $val -eq '') {
            $val = $script:DefaultBranding.$field
        }
        $merged[$field] = $val
    }
    return [PSCustomObject]$merged
}

function Escape-Html {
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][string]$Value)
    return [System.Net.WebUtility]::HtmlEncode($Value)
}

function Escape-Css {
    <#
    .SYNOPSIS
        Sanitises a value before embedding inside a CSS declaration.
    .DESCRIPTION
        Rejects values containing characters that could break out of a CSS
        property value context (semicolons, braces, angle brackets, quotes).
        Returns the value unchanged when it is safe.
    #>
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][string]$Value)
    if ($Value -match '[;{}<>"''\\]') {
        throw [System.ArgumentException]::new("branding.invalid_css_value: value contains disallowed characters: $Value")
    }
    return $Value
}

function Build-CssOverrides {
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][PSCustomObject]$Config)

    $accent  = Escape-Css -Value $Config.PrimaryColour
    $surface = Escape-Css -Value $Config.SurfaceColour
    $text    = Escape-Css -Value $Config.TextColour
    $muted   = Escape-Css -Value $Config.MutedColour

    return @"
<style id="m365-branding-css">
:root {
  --accent: $accent;
  --accent-soft: ${accent}22;
  --surface: $surface;
  --text: $text;
  --muted: $muted;
}
</style>
"@
}

function Build-CoverFragment {
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][PSCustomObject]$Config)

    $logoHtml = ''
    if ($Config.LogoUrl) {
        # Only allow https:// URLs to prevent data: or javascript: injection.
        if ($Config.LogoUrl -notmatch '^https://') {
            throw [System.ArgumentException]::new("branding.invalid_logo_url: LogoUrl must start with https://")
        }
        $escapedSrc = Escape-Html -Value $Config.LogoUrl
        $logoHtml = "<img src=""$escapedSrc"" alt=""Company logo"" class=""m365-branding-logo"" />"
    }

    $watermarkHtml = ''
    if ($Config.WatermarkText) {
        $escapedWm = Escape-Html -Value $Config.WatermarkText
        $watermarkHtml = "<div class=""m365-branding-watermark"" aria-hidden=""true"">$escapedWm</div>"
    }

    if (-not $logoHtml -and -not $watermarkHtml) {
        return ''
    }

    return @"
<div class="m365-branding-cover" aria-hidden="true">$logoHtml$watermarkHtml</div>
"@
}

function Build-FooterFragment {
    [CmdletBinding()]
    [OutputType([string])]
    param([Parameter(Mandatory)][PSCustomObject]$Config)

    $escapedFooter = Escape-Html -Value $Config.FooterText
    $pageNumbers   = if ($Config.ShowPageNumbers) {
        'counter(page) "/" counter(pages)'
    }
    else {
        '""'
    }

    return @"
<style id="m365-branding-footer">
@page {
  margin-bottom: 48px;
}
@page :footer {
  content: "$escapedFooter";
  font-size: 9pt;
  color: var(--muted, #6b7280);
}
@page :right {
  @bottom-right {
    content: $pageNumbers;
    font-size: 9pt;
    color: var(--muted, #6b7280);
  }
}
</style>
"@
}

#endregion
